# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  run-specs:
    docker:
      # specify the version you desire here
      - image: cimg/ruby:3.0.1-node
        environment:
          BUNDLER_VERSION: 2.0.1
          PG_HOST: localhost
          RAILS_ENV: test
          RACK_ENV: test

      - image: postgres:12.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: project_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
          
      - image: circleci/redis:6.0.9-alpine

    steps:
      - checkout

      - run:
          name: Install Packages
          command: |
            sudo apt-get update && sudo apt-get install -y \
            shared-mime-info \
            libxml2-dev \
            libjpeg-dev \
            libpng-dev \
            libxrender-dev \
            libfontconfig

      - restore_cache:
          keys:
            - cachenum-16-bundler-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - cachenum-16-packs-manifest-
      - restore_cache:
          keys:
            - cachenum-16-yarn-{{ checksum "yarn.lock" }}
            
      - run:
          name: Install Bundle & Gems
          no_output_timeout: 30m
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v $BUNDLER_VERSION
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

workflows:
  version: 2
  specs-only:
    jobs:
      - run-specs